name: "NRF24 Receiver"
version: "1.0"
slug: "nrf24_receiver"
description: "Empfängt NRF24-Daten und zeigt sie in den Logs an"
arch:
  - aarch64
  - armv7
startup: application
boot: auto
privileged: true
options: {}
schema: {}
